name: Runs Tests On Code
run-name: Testing and Linting Workspace
on:
  workflow_dispatch:  #Enables the workflow to be manually triggered.
  pull_request:  #Enables the workflow to be automatically after a pull request.
  push:   #Enables the workflow to be automatically after a push to main branch.
    branches:
      - main
# permissions: #Defines permissions for the github token used for this workflow
#   contents: read
#   pull_requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true #Cancels any running job or workflow in the same concurrency group
jobs:
  Lint-Code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Job ${{ job.name }}"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Echo current directory name
        run: echo $PWD
      - name: Navigate to working directory
        run: cd ./teaching-kelechi
      - name: Echo current directory name
        run: echo $PWD
      - name: Setup Node
        working-directory: ./teaching-kelechi
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x #16.13
          cache: npm
      - name: Install Yarn
        run: |
          echo $PWD
          npm install -g yarn
      - name: Install dependencies
        run: |
          cd ./teaching-kelechi
          yarn install --frozen-lockfile
      - name: Run tests
        run: |
          cd ./teaching-kelechi
          yarn run affected-test
      - name: Lint workspace
        run: |
          cd ./teaching-kelechi
          yarn run linting
