name: Runs Tests On Code
run-name: Testing and Linting Workspace
on:
  workflow_dispatch:  #Enables the workflow to be manually triggered.
  pull_request:  #Enables the workflow to be automatically after a pull request.
  push:   #Enables the workflow to be automatically after a push to main branch.
    branches:
      - main
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true #Cancels any running job or workflow in the same concurrency group
jobs:
  Lint-Code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Job ${{ job.name }}"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn run affected-test
      - name: Lint workspace
        run: yarn run linting
      - name: Post status to slack
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: 'C0460G9ESV7'
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
