name: Runs Tests On Code
run-name: Linting Workspace
on:
  workflow_dispatch  #Enables the workflow to be manually triggered.
  pull_request
  push:
    branches:
      - main
permissions: #Defines permissions for the github token used for this workflow
  content: read
  pull_requests: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true #Cancels any running job or workflow in the same concurrency group
jobs:
  Lint Code:
    steps:
      - run: echo "Starting Job ${{ job.name }}"
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 16.13.x
        cache: npm
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn run affected-test
      - name: Lint workspace
        run: yarn run linting
